name: Release
on:
  push:
    branches:
      - main
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Brightspace/third-party-actions@actions/checkout
        with:
          persist-credentials: false

      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: '14'

      - name: Semantic Release
        uses: BrightspaceUI/actions/semantic-release@master
        id: semantic-release
        with:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.D2L_GITHUB_TOKEN }}
          NPM: false

      - name: Get CodeArtifact Authorization Token
        uses: Brightspace/codeartifact-actions/get-authorization-token@v1.5.1
        if: steps.semantic-release.outputs.VERSION != ''
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Publish package
        if: steps.semantic-release.outputs.VERSION != ''
        run: npm publish
